### ISSUE TITLE
rename back to cb-tester?

### ISSUE THREAD

**Issue by jprichardson** [common-blockchain/node-tester#6]
`node-tester` is confusing. It could lead one to believe that the prefix `node` is somehow related to `node.js`. I realize it's in reference to a Blockchain API provider "node", but even that's confusing because we're not testing the provider or "node", but rather the Common Blockchain interface. Unless goals somehow have changed?

**Comment by dcousens** [comment]
@jprichardson I think we should change `node`,  that is the confusing part.   Opening issue in the relevant spot.
